language: node_js
node_js:
- '9'
cache:
  directories:
  - "$HOME/.cache/yarn"
  - ".cache"
dist: trusty
os:
- linux
script:
- yarn test
before_deploy: rm -rf node_modules
deploy:
  provider: heroku
  api_key:
    secure: reOR4ey1iVfwqLLm+aQmBz1zZfBPf4klP+Eh14/0bHq+bbYu33csyCEOYLx1wx1nWC0tWw/04bdximsWEeBbTy1q9dBy2p6zqLai09CmBO4ELXvdzrAVYHi5u9WyzD7CSJTM7pDz6Kn4q49Y/OCKkp+E27C87ECEEpc+AyJOttjtnCYkGnJIIS64LotcaNB1H+PI5p1fmnlHVZTMliBWhjhDYz5T8ThN3/DUFp4rsw4cQYOEdp58twgqPEepTG1kRufucxZh8kG8yXnVChaRi83bvs9FYkwI6PQ1QwZH08MAQxmCTr0G6xt2ijjtlJZUMnpVEM6lFLG3IXpJzk92SDhnhTJ2us8WV82fdCDSRs26unWg5S5YN85FzKNrnXnbPT2WQak3w9FCFaafeAt1Qg7e3S+4W9NXuwfQskEzaFhzWvTGIoyMRtOGUnhq+leDum5X1auv/Lbx/+bzyEam+twyhJ5PXzXF9Rp8QOJHMFk3j/ZDcWrLi5USC4L6RDzfSvsANfITn8mZMLg6In4ByJ/H8AzLceEufEc/Vb2m1HqE5AIyRnKzyBSZ0IbNPAbPIbx2BRnoydmvo8UEe4wtun9gJAfOXwWRN80Rls7iGcbrtxXf45T7X91LUT2YGU16iATPJFJkMON1V2LggwRmDIBe0K4zZoeHFviKaNDVAwU=
  app: apollo-universal-starter-kit
  on:
    repo: sysgears/apollo-universal-starter-kit
