spring:
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
    show-sql: true
  datasource:
    driver-class-name: org.h2.Driver
    password: ''
    url: jdbc:h2:mem:apollo
    username: sa
  h2:
    console:
      enabled: true
      path: /h2-console
graphql:
  servlet:
    async-mode-enabled: true
    exception-handlers-enabled: true
    cors:
      allowed-origins: "*"
      allow-credentials: true
    subscriptions:
      apollo:
        keep-alive-enabled: false
      websocket:
        path: /graphql
graphiql:
  enabled: true
  endpoint:
    subscriptions: /graphql
  mapping: /graphiql